env:
    browser: true
    node: true
    es6: true

parserOptions:
    ecmaVersion: 6
    sourceType: 'module'
    ecmaFeatures:
        jsx: true

plugins:
    - 'react'

rules:
    no-console: [ 'off' ]
    react/jsx-uses-vars: [2]
